tasks:
  greet:
    image: circleci/ruby:2.5
    commands:
      - bundle config path

  rspec:
    image: circleci/ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec

workflow:
  - name: development
    tasks:
      - greet
      - rspec
